services:
  - type: web
    name: dhan-webhook-final
HEAD
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    autoDeploy: true
    envVars:
      - key: DHAN_TOKEN
        value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzUyODQ0NDg2LCJ0b2tlbkNvbnN1bWVyVHlwZSI6IlNFTEYiLCJ3ZWJob29rVXJsIjoiIiwiZGhhbkNsaWVudElkIjoiMTEwNzczNTIwNCJ9.53cHxByglSfkFS48-2_EhYySAnW98Kj4Ck7i4XqV_rKJVcdnPeouuvf64iLyPKUbjEC9nE9Ch5jllH71HbeUzA

    runtime: python
    buildCommand: ""
    startCommand: python webhook_server.py
    envVars:
      - key: DHAN_TOKEN
        sync: false
    plan: free
    region: oregon
 12d9cd4 (Add render.yaml for Render deployement)
