services:
  - type: web
    name: dhan-webhook-final
HEAD
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    autoDeploy: true
    envVars:
      - key: DHAN_TOKEN
        value:

    runtime: python
    buildCommand: ""
    startCommand: python webhook_server.py
    envVars:
      - key: DHAN_TOKEN
        sync: false
    plan: free
    region: oregon
 12d9cd4 (Add render.yaml for Render deployement)
